### ISSUE TITLE
 404 GET /codemirror-minified

### ISSUE THREAD

**Issue by SnowMakerDemo** [spring-projects/spring-flo#40]
npm start ;      [1] 18.11.07 09:57:42 304 GET /rxjs/internal/observable/dom/ajax.js
[1] 18.11.07 09:57:42 304 GET /rxjs/internal/util/root.js
[1] 18.11.07 09:57:42 304 GET /rxjs/internal/util/applyMixins.js
[1] 18.11.07 09:57:46 404 GET /codemirror-minified
[1] 18.11.07 09:57:46 404 GET /codemirror-minified/addon/hint/show-hint
[1] 18.11.07 09:57:46 404 GET /codemirror-minified/addon/scroll/annotatescrollbar
[1] 18.11.07 09:57:46 404 GET /codemirror-minified/addon/display/placeholder[1] 18.11.07 09:57:46 404 GET /codemirror-minified/mode/meta
[1] 18.11.07 09:57:46 404 GET /codemirror-minified/addon/scroll/simplescrollbars
[1] 18.11.07 09:57:46 404 GET /codemirror-minified/addon/edit/matchbrackets
[1] 18.11.07 09:57:46 404 GET /codemirror-minified/addon/lint/lint
[1] 18.11.07 09:57:46 404 GET /codemirror-minified/addon/lint/json-lint
[1] 18.11.07 09:57:46 404 GET /codemirror-minified/addon/lint/javascript-lint

why?

**Comment by BoykoAlex** [comment]
Why codemirror addons are pulled in?
The example has a property editing dialog. The `rabbit` node has a `snippet` property that allows one to enter a code snippet in a language picked in `language` property.

Why 404? Hmm... hard to tell... the example seem to work... What's the context of the 404? Can you point to a project git repo?
Perhaps all you need is delete `node_modules` folder and package-lock.json` and run `npm install` again.

**Comment by BoykoAlex** [comment]
Still having this problem?

**Comment by dmytrobr** [comment]
I have the same issue

**Comment by dmytrobr** [comment]
npm --version
6.4.1

**Comment by dmytrobr** [comment]
I've tried to switch to other GIT branches, but getting the same error. 
On "npm start" command new browser windows opens, but UI is never loaded and I see 404 in both Chrome logs and NodeJS logs

**Comment by dmytrobr** [comment]
What i can is that actual script on the filesystem has .js extension.
ls node_modules/codemirror-minified/addon/hint/show-hint.js 
node_modules/codemirror-minified/addon/hint/show-hint.js

But URL that I see in logs "GET /codemirror-minified/addon/hint/show-hint"

**Comment by BoykoAlex** [comment]
Fixed now. Thanks for reporting this... I have switched to `codemirror-minified` because uglify plugin in webpack fails to uglify `codemirror` lib correctly and instead just corrupts the code.
I had the code in the local branch, published the changes to npm but forgot to merge these changes to master (!!!). Now it should be all in order.

**Comment by frankyaorenjie** [comment]
still the same issue, logs in console after `npm start` said 404 for /codemirror-minified/addon/hint/show-hint

**Comment by BoykoAlex** [comment]
Try now. This commit should have fixed it: ffe5cffec1fe2d19514404e037bec08c41559e57

P.S. Such a mess with `codemirror` -> `codemirror-minified` swicth :-(

**Comment by frankyaorenjie** [comment]
Thanks @BoykoAlex
